// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: bmoccfraiuxcbyygadwe

class SupabaseConfig {
  static const String supabaseUrl = 'https://bmoccfraiuxcbyygadwe.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtb2NjZnJhaXV4Y2J5eWdhZHdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwMjE1ODUsImV4cCI6MjA3NzU5NzU4NX0.nkEKIF6VB_3QzYCNTH8rKQhyK5YoNjGE898ObXx-4kY';
}
